name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set tags
      id: vars
      run: |
        DATE_TAG=$(date +%Y%m%d)
        SHORT_SHA=${GITHUB_SHA::7}
        echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV
        echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        IMAGE=ghcr.io/${{ github.repository }}
        docker build -t $IMAGE:latest -t $IMAGE:${DATE_TAG} -t $IMAGE:${SHORT_SHA} .

    - name: Push Docker image
      run: |
        IMAGE=ghcr.io/${{ github.repository }}
        docker push $IMAGE:latest
        docker push $IMAGE:${DATE_TAG}
        docker push $IMAGE:${SHORT_SHA}
  
